from Library.Lite.litelog import litelog
from Library.Lite.liteconfig import liteconfig
mylog=litelog(name=__name__,style="L")
mycfg=liteconfig("2.cfg",litelog=True)
mycfg.addCfg("key","1")
mycfg.signCfg("key","这是一个注释")
mycfg.addCfg("vau122","abc")
mycfg.signCfg("vau122","这是一个注释")
mycfg.saveCfg()
mycfg.editCfg()
print(mycfg.readCfg("key"))
mycfg=liteconfig("2.lang",litelog=True)
mycfg.addCfg("key","多语言")
mycfg.signCfg("key","这是一个注释")
mycfg.addCfg("vau122","语言适配")
mycfg.signCfg("vau122","这是一个注释")
mycfg.saveCfg()
mycfg.editCfg()
print(mycfg.readCfg("key"))