name: WordPress

on:
  schedule:
    - cron: "30 16 * * *"
  push:	
    branches:	
      - main
job:
  wordpress:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set-up workspace
        run: |
          pip install -r requirements.txt
          pip list
      - name: Post
        run: |
          ${{ github.workspace }}/main.py